spring:
  r2dbc:
    url: "r2dbc:postgresql://store-0.tlotr-db.tlotr-app.svc.cluster.local:5432/tlotr"
    username: "${TLOTR_DB_USERNAME:smeagol}"
    password: "${TLOTR_DB_PASSWORD:my-precious}"
  flyway:
    url: "jdbc:postgresql://store-0.tlotr-db.tlotr-app.svc.cluster.local:5432/tlotr"
    user: "${TLOTR_DB_USERNAME:smeagol}"
    password: "${TLOTR_DB_PASSWORD:my-precious}"